#!/bin/sh

### BEGIN INIT INFO

# Provides:          tightvncserver
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop tightvncserver
### END INIT INFO

### Customize this entry
# Set the USER variable to the name of the user to start tightvncserver under

export USER='pi'

### End customization required
     
eval cd ~$USER

    case "$1" in

      start)

	sleep 3   # wait for pi to finish getting a network
        su $USER -c '/usr/bin/tightvncserver :1 -geometry 800x400'

        echo "Starting TightVNC server for $USER "

        ;;

      stop)

        pkill Xtightvnc

        echo "Tightvncserver stopped"

        ;;

      *)

        echo "Usage: /etc/init.d/tightvncserver {start|stop}"

        exit 1

        ;;

    esac

exit 0


